# Generated by Django 5.1.5 on 2025-02-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('President', 'President'), ('Head Officer', 'Head Officer'), ('Manager', 'Manager'), ('Supervisor', 'Supervisor'), ('Lead Engineer', 'Lead Engineer')], max_length=50)),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='team_images/')),
                ('joined_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
