# Generated by Django 5.1.5 on 2025-02-21 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('bid_amount_range', models.CharField(max_length=100)),
                ('document', models.FileField(upload_to='tender_documents/')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Under Review', 'Under Review'), ('Awarded', 'Awarded')], default='Open', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_details', models.CharField(max_length=200)),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proposal_document', models.FileField(upload_to='bid_documents/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='tender.tender')),
            ],
        ),
    ]
