# Generated by Django 5.1.5 on 2025-02-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Facility Name')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Report Title')),
                ('file', models.FileField(upload_to='financial_reports/', verbose_name='Report File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarineEngineeringFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Faculty Name')),
                ('designation', models.CharField(max_length=100, verbose_name='Designation')),
                ('expertise', models.CharField(max_length=200, verbose_name='Area of Expertise')),
                ('bio', models.TextField(verbose_name='Bio')),
            ],
        ),
        migrations.CreateModel(
            name='ShipBuildingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Budget/Amount')),
                ('preferred_technology', models.CharField(max_length=100, verbose_name='Preferred Shipbuilding Technology')),
                ('ship_type', models.CharField(max_length=50, verbose_name='Ship Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShipRepairComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_model', models.CharField(max_length=100, verbose_name='Ship Model')),
                ('year_of_manufacture', models.PositiveIntegerField(verbose_name='Year of Manufacture')),
                ('ship_type', models.CharField(max_length=50, verbose_name='Ship Type')),
                ('issue_description', models.TextField(verbose_name='Description of the Issue')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
