# Generated by Django 5.1.5 on 2025-02-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarineEngineering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('expertise', models.TextField()),
                ('experience', models.IntegerField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='marine_engineering/')),
            ],
        ),
        migrations.DeleteModel(
            name='MarineEngineeringFaculty',
        ),
    ]
