# Generated by Django 5.1.5 on 2025-02-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_details', models.CharField(blank=True, max_length=100, null=True)),
                ('complaint_type', models.CharField(choices=[('Fraud', 'Fraud'), ('Corruption', 'Corruption'), ('Safety Violation', 'Safety Violation'), ('Harassment', 'Harassment'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='grievance_evidence/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
